/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_benny_ffmpeg_FFmpegPlayer */

#ifndef _Included_com_benny_ffmpeg_FFmpegPlayer
#define _Included_com_benny_ffmpeg_FFmpegPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_benny_ffmpeg_FFmpegPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_benny_ffmpeg_FFmpegPlayer_render
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_benny_ffmpeg_FFmpegPlayer
 * Method:    playAudio
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_benny_ffmpeg_FFmpegPlayer_audio
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
