/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_benny_ffmpeg_FFmpegInfo */

#ifndef _Included_com_benny_ffmpeg_FFmpegInfo
#define _Included_com_benny_ffmpeg_FFmpegInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_benny_ffmpeg_FFmpegInfo
 * Method:    getProtocol
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_benny_ffmpeg_FFmpegInfo_getProtocol
  (JNIEnv *, jclass);

/*
 * Class:     com_benny_ffmpeg_FFmpegInfo
 * Method:    getAVFormat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_benny_ffmpeg_FFmpegInfo_getAVFormat
  (JNIEnv *, jclass);

/*
 * Class:     com_benny_ffmpeg_FFmpegInfo
 * Method:    getAVCodec
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_benny_ffmpeg_FFmpegInfo_getAVCodec
  (JNIEnv *, jclass);

/*
 * Class:     com_benny_ffmpeg_FFmpegInfo
 * Method:    getAVFilter
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_benny_ffmpeg_FFmpegInfo_getAVFilter
  (JNIEnv *, jclass);

/*
 * Class:     com_benny_ffmpeg_FFmpegInfo
 * Method:    getConfigure
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_benny_ffmpeg_FFmpegInfo_getConfigure
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
