/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_benny_ffmpeg_FFmpegMediaPlayer */

#ifndef _Included_com_benny_ffmpeg_FFmpegMediaPlayer
#define _Included_com_benny_ffmpeg_FFmpegMediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_benny_ffmpeg_FFmpegMediaPlayer
 * Method:    player
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_benny_ffmpeg_FFmpegMediaPlayer_player
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
