/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_benny_ffmpeg_FFmpegCode */

#ifndef _Included_com_benny_ffmpeg_FFmpegCode
#define _Included_com_benny_ffmpeg_FFmpegCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_benny_ffmpeg_FFmpegCode
 * Method:    Decode2YUV
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_benny_ffmpeg_FFmpegCode_Decode2YUV
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_benny_ffmpeg_FFmpegCode
 * Method:    Decode2PCM
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_benny_ffmpeg_FFmpegCode_Decode2PCM
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
