/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_benny_fmod_FmodVoice */

#ifndef _Included_com_benny_fmod_FmodVoice
#define _Included_com_benny_fmod_FmodVoice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_benny_fmod_FmodVoice
 * Method:    PlayVoice
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_benny_fmod_FmodVoice_PlayVoice
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_benny_fmod_FmodVoice
 * Method:    Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_benny_fmod_FmodVoice_Stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
