/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_benny_libapp_JNI2Test */

#ifndef _Included_com_benny_libapp_JNI2Test
#define _Included_com_benny_libapp_JNI2Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_benny_libapp_JNI2Test
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_benny_libapp_JNI2Test_getString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
