/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_benny_libapp_JniTest */

#ifndef _Included_com_benny_libapp_JniTest
#define _Included_com_benny_libapp_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_benny_libapp_JniTest
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_benny_libapp_JniTest_getText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
